// Mocks generated by Mockito 5.4.4 from annotations
// in observer_core/test/server_nestjs/data/repositories/server_nestjs_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:observer_core/server_nestjs/feature_server_nestjs_export.dart'
    as _i3;
import 'package:retrofit/dio.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AbstractServerNestjsSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractServerNestjsSource extends _i1.Mock
    implements _i3.AbstractServerNestjsSource {
  MockAbstractServerNestjsSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> get(_i3.GetParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [params],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #get,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> upsert(_i3.UpsertParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsert,
          [params],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #upsert,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> uploadFile(
          _i3.UploadFormDataParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [params],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #uploadFile,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> delete(_i3.DeleteParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [params],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #delete,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> search(_i3.SearchParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [params],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #search,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
}
