// Mocks generated by Mockito 5.4.4 from annotations
// in observer_core/test/server_nestjs/data/sources/in_memory_api_nestjs_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:observer_core/server_nestjs/data/services/in_memory_api_nestjs_service.dart'
    as _i3;
import 'package:retrofit/dio.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InMemoryApiNestjsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInMemoryApiNestjsService extends _i1.Mock
    implements _i3.InMemoryApiNestjsService {
  MockInMemoryApiNestjsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getEnvironments() =>
      (super.noSuchMethod(
        Invocation.method(
          #getEnvironments,
          [],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getEnvironments,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postEnvironments(
          {required String? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #postEnvironments,
          [],
          {#body: body},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postEnvironments,
            [],
            {#body: body},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> searchEnvironments(
          {required String? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEnvironments,
          [],
          {#body: body},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #searchEnvironments,
            [],
            {#body: body},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> searchStrictEnvironments(
          {required String? body}) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchStrictEnvironments,
          [],
          {#body: body},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #searchStrictEnvironments,
            [],
            {#body: body},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
}
