// Mocks generated by Mockito 5.4.4 from annotations
// in observer_core/test/server_nestjs/data/sources/server_nestjs_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:observer_core/server_nestjs/data/services/server_nestjs_service.dart'
    as _i3;
import 'package:retrofit/retrofit.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ServerNestjsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerNestjsService extends _i1.Mock
    implements _i3.ServerNestjsService {
  MockServerNestjsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getHome() => (super.noSuchMethod(
        Invocation.method(
          #getHome,
          [],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getHome,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getEnvironments(
          {required String? authorization}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEnvironments,
          [],
          {#authorization: authorization},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getEnvironments,
            [],
            {#authorization: authorization},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> searchEnvironments({
    required String? authorization,
    required String? contentType,
    String? input = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEnvironments,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #input: input,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #searchEnvironments,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #input: input,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> searchStrictEnvironments({
    required String? authorization,
    required String? contentType,
    String? input = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchStrictEnvironments,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #input: input,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #searchStrictEnvironments,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #input: input,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> upsertEnvironment({
    required String? authorization,
    required String? contentType,
    required String? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertEnvironment,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #upsertEnvironment,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteEnvironment({
    required String? authorization,
    required String? contentType,
    required String? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEnvironment,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteEnvironment,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getCategories(
          {required String? authorization}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
          {#authorization: authorization},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getCategories,
            [],
            {#authorization: authorization},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> searchCategories({
    required String? authorization,
    required String? contentType,
    String? input = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCategories,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #input: input,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #searchCategories,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #input: input,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> searchStrictCategories({
    required String? authorization,
    required String? contentType,
    String? input = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchStrictCategories,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #input: input,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #searchStrictCategories,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #input: input,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> upsertCategory({
    required String? authorization,
    required String? contentType,
    required String? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertCategory,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #upsertCategory,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteCategory({
    required String? authorization,
    required String? contentType,
    required String? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteCategory,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getArticles(
          {required String? authorization}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticles,
          [],
          {#authorization: authorization},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getArticles,
            [],
            {#authorization: authorization},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getProjects(
          {required String? authorization}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjects,
          [],
          {#authorization: authorization},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getProjects,
            [],
            {#authorization: authorization},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> upsertProject({
    required String? authorization,
    required String? contentType,
    required String? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertProject,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #upsertProject,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteProject({
    required String? authorization,
    required String? contentType,
    required String? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProject,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #id: id,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteProject,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #id: id,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getOrganisation(
          {required String? authorization}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrganisation,
          [],
          {#authorization: authorization},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getOrganisation,
            [],
            {#authorization: authorization},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getLegals(
          {required String? authorization}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLegals,
          [],
          {#authorization: authorization},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getLegals,
            [],
            {#authorization: authorization},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getDocuments(
          {required String? authorization}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocuments,
          [],
          {#authorization: authorization},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getDocuments,
            [],
            {#authorization: authorization},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getDocumentsFilteredBy({
    required String? authorization,
    required String? folder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentsFilteredBy,
          [],
          {
            #authorization: authorization,
            #folder: folder,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getDocumentsFilteredBy,
            [],
            {
              #authorization: authorization,
              #folder: folder,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> upsertOneDocument({
    required String? authorization,
    required String? contentType,
    required String? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertOneDocument,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #upsertOneDocument,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> uploadOneDocument({
    required String? authorization,
    required _i5.FormData? formData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadOneDocument,
          [],
          {
            #authorization: authorization,
            #formData: formData,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #uploadOneDocument,
            [],
            {
              #authorization: authorization,
              #formData: formData,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> uploadMultipleDocuments({
    required String? authorization,
    required _i5.FormData? formData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMultipleDocuments,
          [],
          {
            #authorization: authorization,
            #formData: formData,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #uploadMultipleDocuments,
            [],
            {
              #authorization: authorization,
              #formData: formData,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteOneDocument({
    required String? authorization,
    required String? contentType,
    required String? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOneDocument,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #id: id,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteOneDocument,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #id: id,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteMultipleDocuments({
    required String? authorization,
    required String? contentType,
    required String? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMultipleDocuments,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteMultipleDocuments,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getProposedServices(
          {required String? authorization}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProposedServices,
          [],
          {#authorization: authorization},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getProposedServices,
            [],
            {#authorization: authorization},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> upsertOneService({
    required String? authorization,
    required String? contentType,
    required String? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertOneService,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #upsertOneService,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteOneService({
    required String? authorization,
    required String? contentType,
    required String? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOneService,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #id: id,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteOneService,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #id: id,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getSkills(
          {required String? authorization}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSkills,
          [],
          {#authorization: authorization},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getSkills,
            [],
            {#authorization: authorization},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> upsertOneSkill({
    required String? authorization,
    required String? contentType,
    required String? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertOneSkill,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #upsertOneSkill,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteOneSkill({
    required String? authorization,
    required String? contentType,
    required String? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOneSkill,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #id: id,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteOneSkill,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #id: id,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getReasons(
          {required String? authorization}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReasons,
          [],
          {#authorization: authorization},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getReasons,
            [],
            {#authorization: authorization},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> upsertOneReason({
    required String? authorization,
    required String? contentType,
    required String? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertOneReason,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #upsertOneReason,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteOneReason({
    required String? authorization,
    required String? contentType,
    required String? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOneReason,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #id: id,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteOneReason,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #id: id,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getDatasAboutMe(
          {required String? authorization}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDatasAboutMe,
          [],
          {#authorization: authorization},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getDatasAboutMe,
            [],
            {#authorization: authorization},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> upsertAbouts({
    required String? authorization,
    required String? contentType,
    required String? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertAbouts,
          [],
          {
            #authorization: authorization,
            #contentType: contentType,
            #body: body,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #upsertAbouts,
            [],
            {
              #authorization: authorization,
              #contentType: contentType,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
}
