on:
  push:
    branches:
      - main

name: 📎 [MERGE] Création automatique d'un tag.
jobs:
  create-tags:
    #    runs-on: ubuntu-latest
    runs-on: windows-latest
    steps:
      - run: echo "🎉 Bravo 🎉. Le job se lance sur l'évènement ${{ github.event_name }}."
      - run: echo "Le nom de la branche est ${{ github.ref }} et le nom du repository est ${{ github.repository }}."

      - uses: actions/checkout@v3

      - name: Get version from pubspec.yaml
        id: version
        run: |
          $version = (Get-Content pubspec.yaml | Select-String 'version:[^^]*' | ForEach-Object { $_.ToString().Split(":")[1].Trim() })
          echo "APP_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Use the value
        run: |
          echo "${{ env.APP_VERSION }}"

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: observer_core_v${{ env.APP_VERSION }}
          body: ${{ steps.tag_version.outputs.changelog }}
